In [1]:
import tensorflow as tf
import time
import numpy as np
from qopt import *
from qopt.solver_algorithms import Solver
from qopt.tensorflow_cost_func import TensorFlowProcessInfid
from qopt.tensorflow_solver_algs import TensorFlowSolver
from qopt.tensorflow_simulator import TensorFlowSimulator
from qopt.tensorflow_optimize import TensorFlowScipyOptimizer

C:\Users\julia\Documents\qopt\qopt\matrix.py:80: UserWarning: Qutip not installed. plot_bloch_vector_evolution() is not available
  warn('Qutip not installed. plot_bloch_vector_evolution() is not available')
C:\Users\julia\.conda\envs\qopt_tensorflow\lib\site-packages\filter_functions\plotting.py:68: UserWarning: Qutip not installed. plot_bloch_vector_evolution() is not available
  warn('Qutip not installed. plot_bloch_vector_evolution() is not available')
C:\Users\julia\Documents\qopt\qopt\optimize.py:88: UserWarning: simanneal not installed. SimulatedAnnealing is not available
  warn('simanneal not installed. '
C:\Users\julia\Documents\qopt\qopt\plotting.py:55: UserWarning: Qutip not installed. plot_bloch_vector_evolution() is not available
  warn('Qutip not installed. plot_bloch_vector_evolution() is not available')


In [2]:
target = (.5 * DenseOperator.pauli_x()).exp(tau=1 * -1j)

In [ ]:
total_time = np.pi
n_time_steps = int(1e2)
delta_t = total_time / n_time_steps

solver = TensorFlowSolver(
    h_ctrl=[.5 * DenseOperator.pauli_x()],
    h_drift=[0 * DenseOperator.pauli_x()] * n_time_steps,
    tau=delta_t * np.ones(n_time_steps)
)
default_opt_pars = tf.Variable(np.ones((n_time_steps, 1)))

In [1]:
solver.set_optimization_parameters(default_opt_pars)


NameError: name 'solver' is not defined

In [ ]:
solver._create_dyn_gen(np.ones((n_time_steps, 1)))


In [2]:
target = (.5 * DenseOperator.pauli_x()).exp(tau=total_time * -1j)
1 +1

NameError: name 'DenseOperator' is not defined

In [1]:
1 +1

2

In [ ]:
cost_func = TensorFlowProcessInfid(
    solver=solver,
    target=target
)

cost_func.costs()

In [ ]:
target

In [ ]:
solver.forward_propagators[-1]


In [ ]:

solver.dyn_gen[-1]

In [ ]:
solver._compute_forward_propagation()


In [ ]:
solver.tau


In [ ]:


start = time.time()
solver._compute_propagation()
end = time.time()
print(end- start)

In [ ]:
simulator = TensorFlowSimulator(
    solvers=solver,
    cost_funcs=cost_func
)

optimizer = TensorFlowScipyOptimizer(
    simulator
)


In [7]:
from tensorflow_util import convert_to_constant_tensor, DEFAULT_FLOAT_TYPE
import tensorflow_simulator
import tensorflow_solver_algs
import tensorflow_cost_func
import tensorflow_optimize
from importlib import reload
import tensorflow as tf
from qopt import *
import numpy as np
reload(tensorflow_simulator)
reload(tensorflow_solver_algs)
reload(tensorflow_cost_func)
reload(tensorflow_optimize)

n_time_steps = 100
delta_t = np.pi / n_time_steps
target = DenseOperator.pauli_x()

tf.config.run_functions_eagerly(False)

solver = tensorflow_solver_algs.TensorFlowSolver(
    h_ctrl=[.5 * DenseOperator.pauli_x()],
    h_drift=[0 * DenseOperator.pauli_x()] * n_time_steps,
    tau=delta_t * np.ones(n_time_steps)
)

cost_func = tensorflow_cost_func.TensorFlowProcessInfid(
    solver=solver,
    target=target
)

simulator = tensorflow_simulator.TensorFlowSimulator(
    solver=solver,
    cost_func=cost_func
)

opt_pars = tf.Variable(
    .5 * np.ones((n_time_steps, 1)),
    dtype=DEFAULT_FLOAT_TYPE,
    trainable=True
)

val, grad = simulator.value_and_gradient(opt_pars)
val,grad

(<tf.Tensor: shape=(), dtype=float64, numpy=2.2648549702353193e-14>,
 <tf.Tensor: shape=(100, 1), dtype=float64, numpy=
 array([[-2.36374655e-18],
        [-2.36374655e-18],
        [-2.23801535e-18],
        [-2.11228415e-18],
        [-2.51462399e-18],
        [-2.48947775e-18],
        [-2.69064767e-18],
        [-2.89181759e-18],
        [-2.31345407e-18],
        [-3.04269503e-18],
        [-3.62105855e-18],
        [-3.99825215e-18],
        [-4.40059199e-18],
        [-4.87837054e-18],
        [-4.80293182e-18],
        [-5.23041790e-18],
        [-3.47018111e-18],
        [-2.59006271e-18],
        [-4.40059199e-18],
        [-4.37544575e-18],
        [-5.20527166e-18],
        [-5.15497918e-18],
        [-5.10468670e-18],
        [-5.11725982e-18],
        [-5.11725982e-18],
        [-5.16755230e-18],
        [-6.92778910e-18],
        [-4.36287263e-18],
        [-3.48275423e-18],
        [-2.65292831e-18],
        [-1.74766367e-18],
        [-8.56309648e-19],
        [-1.3374

In [67]:
cost_func.costs(opt_pars)

<tf.Tensor: shape=(), dtype=float64, numpy=0.997566748859703>

In [5]:
optimizer = tensorflow_optimize.TensorFlowScipyOptimizer(simulator=simulator)

result = optimizer.run_optimization(opt_pars)

C:\Users\julia\.conda\envs\qopt_tensorflow\lib\site-packages\scipy\optimize\_differentiable_functions.py:107: ComplexWarning: Casting complex values to real discards the imaginary part
  self.x = np.atleast_1d(x0).astype(float)
C:\Users\julia\.conda\envs\qopt_tensorflow\lib\site-packages\scipy\optimize\lbfgsb.py:334: ComplexWarning: Casting complex values to real discards the imaginary part
  x = array(x0, float64)


In [6]:
result

      fun: 5.376810108259633e-12
 hess_inv: <100x100 LbfgsInvHessProduct with dtype=float64>
      jac: array([-7.28232434e-08, -7.28232434e-08, -7.28232434e-08, -7.28232434e-08,
       -7.28232434e-08, -7.28232434e-08, -7.28232434e-08, -7.28232434e-08,
       -7.28232434e-08, -7.28232434e-08, -7.28232434e-08, -7.28232434e-08,
       -7.28232434e-08, -7.28232434e-08, -7.28232434e-08, -7.28232434e-08,
       -7.28232434e-08, -7.28232434e-08, -7.28232434e-08, -7.28232434e-08,
       -7.28232434e-08, -7.28232434e-08, -7.28232434e-08, -7.28232434e-08,
       -7.28232434e-08, -7.28232434e-08, -7.28232434e-08, -7.28232434e-08,
       -7.28232434e-08, -7.28232434e-08, -7.28232434e-08, -7.28232434e-08,
       -7.28232434e-08, -7.28232434e-08, -7.28232434e-08, -7.28232434e-08,
       -7.28232434e-08, -7.28232434e-08, -7.28232434e-08, -7.28232434e-08,
       -7.28232434e-08, -7.28232434e-08, -7.28232434e-08, -7.28232434e-08,
       -7.28232434e-08, -7.28232434e-08, -7.28232434e-08, -7.28232434e-

In [34]:
with tf.GradientTape() as tape:
    tape.watch(opt_pars)
    forward_propagators = solver.set_optimization_parameters(opt_pars)
    gradient = tape.gradient(forward_propagators, opt_pars)

In [36]:
gradient

<tf.Tensor: shape=(100, 1), dtype=complex128, numpy=
array([[1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0.j],
       [1.+0

In [ ]:
convert_to_constant_tensor(convert_to_constant_tensor(np.zeros((n_time_steps, 1))))

In [ ]:
optimizer.run_optimization(
    initial_opt_pars=tf.constant(convert_to_constant_tensor(np.zeros(n_time_steps)))
)