In [1]:
import tensorflow as tf
import numpy as np
from qopt.tensorflow_util import DEFAULT_FLOAT_TYPE, DEFAULT_COMPLEX_TYPE

C:\Users\julia\Documents\qopt\qopt\matrix.py:80: UserWarning: Qutip not installed. plot_bloch_vector_evolution() is not available
  warn('Qutip not installed. plot_bloch_vector_evolution() is not available')
C:\Users\julia\.conda\envs\qopt_tensorflow\lib\site-packages\filter_functions\plotting.py:68: UserWarning: Qutip not installed. plot_bloch_vector_evolution() is not available
  warn('Qutip not installed. plot_bloch_vector_evolution() is not available')
C:\Users\julia\Documents\qopt\qopt\optimize.py:88: UserWarning: simanneal not installed. SimulatedAnnealing is not available
  warn('simanneal not installed. '
C:\Users\julia\Documents\qopt\qopt\plotting.py:55: UserWarning: Qutip not installed. plot_bloch_vector_evolution() is not available
  warn('Qutip not installed. plot_bloch_vector_evolution() is not available')


In [2]:
pauli_x = tf.constant(
    np.asarray([[0, 1], [1, 0]]), dtype=DEFAULT_COMPLEX_TYPE
)
pauli_x

<tf.Tensor: shape=(2, 2), dtype=complex128, numpy=
array([[0.+0.j, 1.+0.j],
       [1.+0.j, 0.+0.j]])>

In [6]:
def process_fidelity(x):
    total_amp = tf.math.reduce_sum(x)
    print(total_amp)
    dyn_gen = total_amp * pauli_x * 1j
    propagator = tf.linalg.expm(dyn_gen)
    fidelity = tf.linalg.trace(pauli_x @ propagator)
    fidelity = fidelity * tf.math.conj(fidelity) / 4
    fidelity = tf.math.real(fidelity)
    return fidelity

In [7]:
process_fidelity(.5 * np.pi)

tf.Tensor(1.5707964, shape=(), dtype=float32)


InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a float tensor but is a complex128 tensor [Op:Mul]

In [14]:
n = 2
phi = tf.Variable(0.25 * np.pi / n / n * np.ones((n, n), dtype=float), dtype=DEFAULT_FLOAT_TYPE)
with tf.GradientTape() as tape:
    tape.watch(phi)
    fid = process_fidelity(phi)
    gradient = tape.gradient(fid, phi)

tf.Tensor((0.7853981633974483+0j), shape=(), dtype=complex128)


In [15]:
gradient

<tf.Tensor: shape=(2, 2), dtype=complex128, numpy=
array([[1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j]])>

In [16]:
fid

<tf.Tensor: shape=(), dtype=float64, numpy=0.4999999999999999>

In [2]:
import unittest
import tensorflow as tf
import numpy as np
import qopt.tensorflow_cost_func
import qopt.tensorflow_util
from qopt import *

C:\Users\julia\Documents\qopt\qopt\matrix.py:80: UserWarning: Qutip not installed. plot_bloch_vector_evolution() is not available
  warn('Qutip not installed. plot_bloch_vector_evolution() is not available')
C:\Users\julia\.conda\envs\qopt_tensorflow\lib\site-packages\filter_functions\plotting.py:68: UserWarning: Qutip not installed. plot_bloch_vector_evolution() is not available
  warn('Qutip not installed. plot_bloch_vector_evolution() is not available')
C:\Users\julia\Documents\qopt\qopt\optimize.py:88: UserWarning: simanneal not installed. SimulatedAnnealing is not available
  warn('simanneal not installed. '
C:\Users\julia\Documents\qopt\qopt\plotting.py:55: UserWarning: Qutip not installed. plot_bloch_vector_evolution() is not available
  warn('Qutip not installed. plot_bloch_vector_evolution() is not available')


In [2]:
target_matrix = (.5 * DenseOperator.pauli_x()).exp(-1j * np.pi)
target_matrix_adj = target_matrix.dag()
target_matrix_adj_tf = tf.constant(
    target_matrix_adj.data,
    dtype=qopt.tensorflow_util.DEFAULT_COMPLEX_TYPE
)

sample_matrices = []
for phi in [0, .5, 1]:
    sample_matrices.append(
        (.5 * DenseOperator.pauli_x()).exp(1j * phi * np.pi)
    )

sample_matrices_tf = [
    tf.constant(sm.data, dtype=qopt.tensorflow_util.DEFAULT_FLOAT_TYPE)
    for sm in sample_matrices
]

for i in range(len(sample_matrices)):
    print(
        qopt.tensorflow_cost_func.process_fid_unitary(
            propagator=sample_matrices_tf[i],
            target_unitary_adj=target_matrix_adj_tf,
            inverse_dim_squared=.25
        )
    )
print(1 + 1)

NameError: name 'DenseOperator' is not defined

In [1]:
# This will crash
import tensorflow as tf
import numpy as np
from qopt import *  # it does not help to just import DenseOperator

target_matrix = (.5 * DenseOperator.pauli_x()).exp(-1j * np.pi)  # using the method 'first_order' does not crash, but spectral and Frechet do
tf.constant(np.eye(2))

C:\Users\julia\Documents\qopt\qopt\matrix.py:80: UserWarning: Qutip not installed. plot_bloch_vector_evolution() is not available
  warn('Qutip not installed. plot_bloch_vector_evolution() is not available')
C:\Users\julia\.conda\envs\qopt_tensorflow\lib\site-packages\filter_functions\plotting.py:68: UserWarning: Qutip not installed. plot_bloch_vector_evolution() is not available
  warn('Qutip not installed. plot_bloch_vector_evolution() is not available')
C:\Users\julia\Documents\qopt\qopt\optimize.py:88: UserWarning: simanneal not installed. SimulatedAnnealing is not available
  warn('simanneal not installed. '
C:\Users\julia\Documents\qopt\qopt\plotting.py:55: UserWarning: Qutip not installed. plot_bloch_vector_evolution() is not available
  warn('Qutip not installed. plot_bloch_vector_evolution() is not available')


<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 0.],
       [0., 1.]])>

In [ ]:
import tensorflow as tf
import numpy as np
from qopt.matrix import DenseOperator

target_matrix = (.5 * DenseOperator.pauli_x()).exp(-1j * np.pi)
tf.constant(np.eye(2))

In [ ]:
# This will work
import tensorflow as tf
import numpy as np
from qopt import *

target_matrix = (.5 * DenseOperator.pauli_x())
tf.constant(np.eye(2))

In [4]:
import tensorflow as tf
import numpy as np
from qopt import *

tf.constant(np.eye(2))

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 0.],
       [0., 1.]])>